CREATE TABLE `NUMBERING_LEDGER` (
  `NUMBERING_CD` varchar(3) NOT NULL,
  `AVAIL_YEAR` varchar(4) NOT NULL,
  `NEXTNO` decimal(9,0) DEFAULT NULL,
  `DIGITS` decimal(9,0) DEFAULT NULL,
  `UPDUSR` bigint(9) unsigned zerofill DEFAULT NULL,
  `UPDDATE` date DEFAULT NULL,
  PRIMARY KEY (`NUMBERING_CD`,`AVAIL_YEAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8