CREATE TABLE TOPICS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    SUBJECT         VARCHAR(128) DEFAULT NULL,
    CREATEDBY       VARCHAR(8) DEFAULT NULL,
    CREATEDAT        DATE DEFAULT NULL,
    PRIMARY KEY (TOPICNO)
)ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE POSTS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    POSTNO          BIGINT(8) UNSIGNED ZEROFILL,
    POST            VARCHAR(1280) DEFAULT NULL,
    CREATEDBY       VARCHAR(8) DEFAULT NULL,
    CREATEDAT       DATE DEFAULT NULL,
    PRIMARY KEY (TOPICNO, POSTNO)
)ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE POST_RATINGS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    POSTNO          BIGINT(8) UNSIGNED ZEROFILL NOT NULL,
    RATEDBY         VARCHAR(8) NOT NULL,
    RATING_FLG      TINYINT DEFAULT NULL,
    RATEDAT         DATE DEFAULT NULL,
    PRIMARY KEY(TOPICNO, POSTNO, RATEDBY)
)ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;